### ISSUE TITLE
eplus:run failed

### ISSUE THREAD

**Issue by oceanwap** [MaraniMatias/grunt-electron-packager-builder#2]
Loading "task-electron.js" tasks...ERROR
>> TypeError: require(...).init is not a function
Warning: Task "eplus:run" failed. Use --force to continue.

Please help.

**Comment by MaraniMatias** [comment]
I always use this task.

**Comment by oceanwap** [comment]
Yes.
My package.json

{
  "private": true,
  "devDependencies": {
    "apache-server-configs": "^2.8.0",
    "clean-css": "^3.4.9",
    "connect-livereload": "^0.4.0",
    "electron-builder": "^3.5.0",
    "electron-packager": "^6.0.2",
    "electron-prebuilt": "^0.37.5",
    "grunt": "^0.4.5",
    "grunt-concurrent": "^2.1.0",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-compass": "^1.0.0",
    "grunt-contrib-concat": "^0.5.0",
    "grunt-contrib-connect": "^0.8.0",
    "grunt-contrib-copy": "^0.5.0",
    "grunt-contrib-cssmin": "^0.10.0",
    "grunt-contrib-htmlmin": "^0.3.0",
    "grunt-contrib-imagemin": "^0.9.4",
    "grunt-contrib-jshint": "^0.10.0",
    "grunt-contrib-jst": "^0.6.0",
    "grunt-contrib-requirejs": "^0.4.4",
    "grunt-contrib-uglify": "^0.6.0",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-electron-packager-builder": "0.0.6",
    "grunt-filerev": "^2.1.2",
    "grunt-google-cdn": "^0.4.3",
    "grunt-jscs": "^1.8.0",
    "grunt-mocha": "^0.4.11",
    "grunt-newer": "^1.1.0",
    "grunt-normalize-image-uris": "^0.1.2",
    "grunt-open": "^0.2.3",
    "grunt-postcss": "^0.5.5",
    "grunt-rev": "^0.1.0",
    "grunt-sass": "^1.1.0",
    "grunt-usemin": "^2.4.0",
    "grunt-wiredep": "^2.0.0",
    "jit-grunt": "^0.9.1",
    "jshint-stylish": "^1.0.0",
    "load-grunt-config": "^0.19.1",
    "time-grunt": "^1.0.0"
  },
  "engines": {
    "node": ">=5.5.0"
  },
  "dependencies": {
    "grunt-contrib-requirejs": "^0.4.4",
    "jshint-stylish": "^1.0.2",
    "time-grunt": "^1.3.0"
  }
}

**Comment by oceanwap** [comment]
May be you are using some specific version of electron-builder. Because when I try to run init() in node console it gives me error, unknown function.

```
> var e = require('electron-builder')
undefined
> e
{ Packager: [Function: Packager],
  build: [Function: build],
  createPublisher: [Function: createPublisher],
  Platform: 
   { [Function: Platform]
     OSX: Platform { name: 'osx', buildConfigurationKey: 'osx', nodeName: 'darwin' },
     LINUX: 
      Platform {
        name: 'linux',
        buildConfigurationKey: 'linux',
        nodeName: 'linux' },
     WINDOWS: 
      Platform {
        name: 'windows',
        buildConfigurationKey: 'win',
        nodeName: 'win32' } },
  getProductName: [Function: getProductName] }
> e.init()
TypeError: e.init is not a function
    at repl:1:-59
    at REPLServer.defaultEval (repl.js:269:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:439:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)
    at ReadStream.onkeypress (readline.js:106:10)
    at emitTwo (events.js:100:13)
    at ReadStream.emit (events.js:185:7)
    at emitKeys (readline.js:1251:14)
    at [object Generator].next (native)
    at ReadStream.onData (readline.js:919:36)
    at emitOne (events.js:90:13)
    at ReadStream.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at ReadStream.Readable.push (_stream_readable.js:111:10)
    at TTY.onread (net.js:529:20)
```

Can you tell me what version are you using?

**Comment by oceanwap** [comment]
Just removed init() in task-electron.js it started working. You can put a check their for compatibility with older versions if init is defined only then run init.

**Comment by MaraniMatias** [comment]
Thank you
my dependencies
  "devDependencies": {
    "chai": "^3.4.1",
    "colors": "^1.1.2",
    "electron-builder": "^2.7.1",
    "electron-packager": "^5.2.1",
    "electron-prebuilt": "^0.37.5",
    "grunt": "^0.4.5",
    "grunt-contrib-jade": "^0.15.0",
    "grunt-contrib-jshint": "^0.12.0",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-docco-plus": "^1.0.0",
    "grunt-electron-packager-builder": "0.0.5",
    "grunt-mocha-test": "^0.12.7",
    "jade": "^1.11.0",
    "jshint": "^2.9.1",
    "jshint-stylish": "^2.1.0",
    "load-grunt-tasks": "^3.4.0",
    "mocha": "^2.3.4",
    "zombie": "^4.2.1"
  },

I will update them and see what happens

**Comment by MaraniMatias** [comment]
I test the other tasks and  update dependencies
